stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  #DOCKER_REGISTRY: registry.gitlab.com
  #DOCKER_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DOCKER_USER_NAME: CI-token
  DOCKER_REGISTRY: https://registry.teadal.ubiwhere.com
  DOCKER_IMAGE: registry.teadal.ubiwhere.com/teadal-public-images/$CI_PROJECT_NAME

build-docker:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      alias: docker
  
  # override (empty) the global before_script
  before_script: []
  script:
    - docker login -u "$DOCKER_USER_NAME" -p "$REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
    - docker build -t "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"  .
    - docker tag "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
    - docker push "$DOCKER_IMAGE:latest"

build-python:
  stage: build
  image: python:3.12
  before_script:
    - python --version
    - pip install build
  script:
    - python -m build
