# syntax=docker/dockerfile:1.3
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# need git to pill from the asg-runtime repo
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git openssh-client && \
    rm -rf /var/lib/apt/lists/*

# Add GitLab host key to known_hosts
RUN mkdir -p ~/.ssh && \
ssh-keyscan gitlab.teadal.ubiwhere.com >> ~/.ssh/known_hosts

# Install Python dependencies
RUN --mount=type=ssh pip install --no-cache-dir \
    fastapi \
    uvicorn \
    git+ssh://git@gitlab.teadal.ubiwhere.com/teadal-tech/asg-runtime.git

# Copy app source code
COPY app.py .
COPY transforms ./transforms

# Expose FastAPI port
EXPOSE 8000

# Command to run the app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

