# syntax=docker/dockerfile:1
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# need git to pill from the asg-runtime repo
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY reqs_from_gh_src.txt .
RUN pip install --no-cache-dir -r reqs_from_gh_src.txt

# Copy app source code
COPY app.py .
COPY transforms ./transforms

# Expose FastAPI port
EXPOSE 8000

# Command to run the app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

